name       : eventviews
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/eventviews-21.04.1.tar.xz : 9035a353f4191992e96e1646feb20dbe5b47303f8e6e9045e8b38ba6311fa1e0
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kmime-devel
    - kservice-devel
    - kxmlgui-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - kcalutils-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
