name       : eventviews
version    : 20.12.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/eventviews-20.12.2.tar.xz : 69dc2fe3c593e9387ac244b75ac7653f1fc6bee2865c8c412d44972520c48abc
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kmime-devel
    - kservice-devel
    - kxmlgui-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - kcalutils-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
