name       : eventviews
version    : 21.04.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/eventviews-21.04.0.tar.xz : bbd80c0c5c078d0a539cfa43f3b3414e05cae2b2ec9b0d6d986702fa9c3c09ff
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kmime-devel
    - kservice-devel
    - kxmlgui-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - kcalutils-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
