name       : eventviews
version    : 19.04.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/eventviews-19.04.1.tar.xz : 1fae8263d17a802393e5b1ece80879b66303f4d5bc8cc040cf142d6d5e8cc763
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
