name       : eventviews
version    : 18.08.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/eventviews-18.08.0.tar.xz : 925997baf7ab89d736b073894a74699bb0e9e5e679030d98b1c26bfc5b4a44b1
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
