name       : eventviews
version    : 18.04.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/eventviews-18.04.0.tar.xz : c315bbadd653890e7ec667e77b6efb82e1abdc3474d8760a503fe6e75311202a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Library for creating events.
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
