name       : eventviews
version    : 20.04.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/eventviews-20.04.2.tar.xz : 44306f7c20aef2c168d7ed6ca8e3919e5be03dee2fec9e26c6461ca9b6d8c70f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
