name       : eventviews
version    : 21.08.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/eventviews-21.08.2.tar.xz : b28f3a6823194a6a64d8e6043ff4c8ec1897e47b3cc4404cda4aceafec842a34
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kmime-devel
    - kservice-devel
    - kxmlgui-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - kcalutils-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
