name       : eventviews
version    : 18.08.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/eventviews-18.08.2.tar.xz : d9e816cf27b00510e946fad5f1e8c601dc14715c35f7c5475cb4458d39d345a5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
