name       : eventviews
version    : 20.04.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/eventviews-20.04.0.tar.xz : 789b2eaafb57f0b0778515df9fc14f0b7d4554b60948ffe82a8d6b9465b3e343
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - calendarsupport-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdiagram-devel
    - kguiaddons-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kmime-devel
    - kpimtextedit-devel
    - kservice-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
